image: debian:stable

before_script:
  - apt-get update && apt-get -y install texi2html

pages:
  stage: deploy
  - mkdir -p html && (cd html && texi2html ../doc/chopstx.texi)
  - mv html/ public
  artifacts:
    paths:
    - public
  only:
    - master
